# Generated by Django 5.2.8 on 2025-11-27 14:50

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("railroad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destined_routes",
                to="railroad.station",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="distance",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sourced_routes",
                to="railroad.station",
            ),
        ),
    ]
