# Generated by Django 5.2.8 on 2025-11-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0002_route_destination_route_distance_alter_route_source",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="route",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source__exact",
                        models.F("destination"),
                    ),
                    _negated=True,
                ),
                name="source_not_equal_destination_constraint",
            ),
        ),
    ]
