# Generated by Django 5.2.8 on 2025-11-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0003_route_source_not_equal_destination_constraint",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="station",
            name="unique_latitude_longitude",
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(
                max_length=255, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"),
                name="unique_all_stations",
                violation_error_code=400,
                violation_error_message="Such Station already exists",
            ),
        ),
    ]
