# Generated by Django 5.2.8 on 2025-11-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railroad", "0005_traintype_train"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255),
                ),
            ],
        ),
    ]
