# Generated by Django 5.2.8 on 2025-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railroad", "0007_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, null=True
            ),
        ),
    ]
