# Generated by Django 5.2.8 on 2025-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railroad", "0009_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
