# Generated by Django 5.2.8 on 2025-11-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railroad", "0011_journey"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="railroad.journey",
            ),
        ),
    ]
