# Generated by Django 5.2.8 on 2025-11-28 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0013_alter_crew_journey_alter_journey_route_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=(
                    "cargo",
                    "seat",
                    "journey_id",
                    "order_id",
                ),
                name="unique_every_ticket",
            ),
        ),
    ]
