# Generated by Django 5.2.8 on 2025-11-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0014_alter_route_distance_ticket_unique_every_ticket",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_every_ticket",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("cargo", "seat", "journey_id"),
                name="unique_every_ticket",
            ),
        ),
    ]
