# Generated by Django 5.2.8 on 2025-11-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0015_remove_ticket_unique_every_ticket_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ("journey__departure_time",)
            },
        ),
    ]
