# Generated by Django 5.2.8 on 2025-11-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railroad", "0016_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="ticket",
            name="unique_every_ticket",
            constraint=models.UniqueConstraint(
                fields=("cargo", "seat", "journey_id"),
                name="unique_every_ticket",
                violation_error_code=400,
                violation_error_message="Such ticket already exists",
            ),
        ),
    ]
