# Generated by Django 5.2.8 on 2025-11-29 19:47

from django.db import migrations, models

import railroad.image_path


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0017_alter_ticket_unique_every_ticket",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=railroad.image_path.path_to_media,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=railroad.image_path.path_to_media,
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=railroad.image_path.path_to_media,
            ),
        ),
    ]
