# Generated by Django 5.2.8 on 2025-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railroad", "0018_crew_image_station_image_train_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_every_ticket",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("cargo", "seat", "journey"),
                name="unique_every_ticket",
                violation_error_code=400,
                violation_error_message="Such ticket already exists",
            ),
        ),
    ]
