# Generated by Django 5.2.8 on 2025-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0019_remove_ticket_unique_every_ticket_and_more",
        ),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="ticket",
            name="unique_every_ticket",
            constraint=models.UniqueConstraint(
                fields=("cargo", "seat", "journey"),
                name="unique_every_ticket",
                violation_error_code=402,
            ),
        ),
    ]
