# Generated by Django 5.2.8 on 2025-11-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("railroad", "0020_alter_ticket_unique_every_ticket"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="station",
            name="unique_all_stations",
        ),
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_every_ticket",
        ),
    ]
