# Generated by Django 5.2.8 on 2025-11-30 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0022_alter_route_distance_station_unique_all_stations_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="cargo_num",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="places_in_cargo",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0
                    )
                ]
            ),
        ),
    ]
