# Generated by Django 5.2.8 on 2025-11-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "railroad",
            "0023_alter_train_cargo_num_alter_train_places_in_cargo",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="cargo_num",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="places_in_cargo",
            field=models.IntegerField(),
        ),
    ]
